/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xyfkwfbpwqpihokegjbr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5Zmt3ZmJwd3FwaWhva2VnamJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0Njk0MjEsImV4cCI6MjA3NjA0NTQyMX0.g-HtFUuVZb2O8wWRCV-_dHtNO0XUBZ0hF3NDP5ZkLpk"